// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhppOoqCSoVxB3Fis01KhoElZNg7sh7bk',
    appId: '1:341017981931:web:be6598f12cd0bef39cdfae',
    messagingSenderId: '341017981931',
    projectId: 'evogramsocialmedia-6e6e0',
    authDomain: 'evogramsocialmedia-6e6e0.firebaseapp.com',
    storageBucket: 'evogramsocialmedia-6e6e0.appspot.com',
    measurementId: 'G-RPKEBQ9ZDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEplu0BKXpmknCv8DE85s7jjAYvRGrMXo',
    appId: '1:341017981931:android:54c91b36a595fb149cdfae',
    messagingSenderId: '341017981931',
    projectId: 'evogramsocialmedia-6e6e0',
    storageBucket: 'evogramsocialmedia-6e6e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvStZBw2uwJUfIG7DZs2mE7GJJWugSmM',
    appId: '1:341017981931:ios:b16e494ef1c6fef69cdfae',
    messagingSenderId: '341017981931',
    projectId: 'evogramsocialmedia-6e6e0',
    storageBucket: 'evogramsocialmedia-6e6e0.appspot.com',
    iosBundleId: 'com.example.evogram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvStZBw2uwJUfIG7DZs2mE7GJJWugSmM',
    appId: '1:341017981931:ios:b16e494ef1c6fef69cdfae',
    messagingSenderId: '341017981931',
    projectId: 'evogramsocialmedia-6e6e0',
    storageBucket: 'evogramsocialmedia-6e6e0.appspot.com',
    iosBundleId: 'com.example.evogram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhppOoqCSoVxB3Fis01KhoElZNg7sh7bk',
    appId: '1:341017981931:web:32284bff5690e1b59cdfae',
    messagingSenderId: '341017981931',
    projectId: 'evogramsocialmedia-6e6e0',
    authDomain: 'evogramsocialmedia-6e6e0.firebaseapp.com',
    storageBucket: 'evogramsocialmedia-6e6e0.appspot.com',
    measurementId: 'G-H6V896NT2R',
  );
}
